#pragma once
#ifndef __TRUCK_ANIMATION_STATE__
#define __TRUCK_ANIMATION_STATE__

enum TruckAnimationState
{
	TRUCK_IDLE_RIGHT,
	TRUCK_IDLE_LEFT,
	TRUCK_DRIVE_RIGHT,
	TRUCK_DRIVE_LEFT,
	TRUCK_DRIVE_UP,
	TRUCK_DRIVE_DOWN,
	NUM_OF_ANIMATION_STATES
};

#endif 